package sap_api_output_formatter

type SalesOrder struct {
	ConnectionKey string `json:"connection_key"`
	Result        bool   `json:"result"`
	RedisKey      string `json:"redis_key"`
	Filepath      string `json:"filepath"`
	APISchema     string `json:"api_schema"`
	SalesOrder    string `json:"sales_order"`
	Deleted       bool   `json:"deleted"`
}
type Header struct {
	SalesOrder                     string `json:"SalesOrder"`
	SalesOrderType                 string `json:"SalesOrderType"`
	SalesOrganization              string `json:"SalesOrganization"`
	DistributionChannel            string `json:"DistributionChannel"`
	OrganizationDivision           string `json:"OrganizationDivision"`
	SalesGroup                     string `json:"SalesGroup"`
	SalesOffice                    string `json:"SalesOffice"`
	SalesDistrict                  string `json:"SalesDistrict"`
	SoldToParty                    string `json:"SoldToParty"`
	CreationDate                   string `json:"CreationDate"`
	LastChangeDate                 string `json:"LastChangeDate"`
	ExternalDocumentID             string `json:"ExternalDocumentID"`
	LastChangeDateTime             string `json:"LastChangeDateTime"`
	PurchaseOrderByCustomer        string `json:"PurchaseOrderByCustomer"`
	CustomerPurchaseOrderDate      string `json:"CustomerPurchaseOrderDate"`
	SalesOrderDate                 string `json:"SalesOrderDate"`
	TotalNetAmount                 string `json:"TotalNetAmount"`
	OverallDeliveryStatus          string `json:"OverallDeliveryStatus"`
	TotalBlockStatus               string `json:"TotalBlockStatus"`
	OverallOrdReltdBillgStatus     string `json:"OverallOrdReltdBillgStatus"`
	OverallSDDocReferenceStatus    string `json:"OverallSDDocReferenceStatus"`
	TransactionCurrency            string `json:"TransactionCurrency"`
	SDDocumentReason               string `json:"SDDocumentReason"`
	PricingDate                    string `json:"PricingDate"`
	PriceDetnExchangeRate          string `json:"PriceDetnExchangeRate"`
	RequestedDeliveryDate          string `json:"RequestedDeliveryDate"`
	ShippingCondition              string `json:"ShippingCondition"`
	CompleteDeliveryIsDefined      bool   `json:"CompleteDeliveryIsDefined"`
	ShippingType                   string `json:"ShippingType"`
	HeaderBillingBlockReason       string `json:"HeaderBillingBlockReason"`
	DeliveryBlockReason            string `json:"DeliveryBlockReason"`
	IncotermsClassification        string `json:"IncotermsClassification"`
	CustomerPriceGroup             string `json:"CustomerPriceGroup"`
	PriceListType                  string `json:"PriceListType"`
	CustomerPaymentTerms           string `json:"CustomerPaymentTerms"`
	PaymentMethod                  string `json:"PaymentMethod"`
	ReferenceSDDocument            string `json:"ReferenceSDDocument"`
	ReferenceSDDocumentCategory    string `json:"ReferenceSDDocumentCategory"`
	CustomerAccountAssignmentGroup string `json:"CustomerAccountAssignmentGroup"`
	AccountingExchangeRate         string `json:"AccountingExchangeRate"`
	CustomerGroup                  string `json:"CustomerGroup"`
	AdditionalCustomerGroup1       string `json:"AdditionalCustomerGroup1"`
	AdditionalCustomerGroup2       string `json:"AdditionalCustomerGroup2"`
	AdditionalCustomerGroup3       string `json:"AdditionalCustomerGroup3"`
	AdditionalCustomerGroup4       string `json:"AdditionalCustomerGroup4"`
	AdditionalCustomerGroup5       string `json:"AdditionalCustomerGroup5"`
	CustomerTaxClassification1     string `json:"CustomerTaxClassification1"`
	TotalCreditCheckStatus         string `json:"TotalCreditCheckStatus"`
	BillingDocumentDate            string `json:"BillingDocumentDate"`
}

type Item struct {
	SalesOrder                  string `json:"SalesOrder"`
	SalesOrderItem              string `json:"SalesOrderItem"`
	SalesOrderItemCategory      string `json:"SalesOrderItemCategory"`
	SalesOrderItemText          string `json:"SalesOrderItemText"`
	PurchaseOrderByCustomer     string `json:"PurchaseOrderByCustomer"`
	Material                    string `json:"Material"`
	MaterialByCustomer          string `json:"MaterialByCustomer"`
	PricingDate                 string `json:"PricingDate"`
	BillingPlan                 string `json:"BillingPlan"`
	RequestedQuantity           string `json:"RequestedQuantity"`
	RequestedQuantityUnit       string `json:"RequestedQuantityUnit"`
	OrderQuantityUnit           string `json:"OrderQuantityUnit"`
	ConfdDelivQtyInOrderQtyUnit string `json:"ConfdDelivQtyInOrderQtyUnit"`
	ItemGrossWeight             string `json:"ItemGrossWeight"`
	ItemNetWeight               string `json:"ItemNetWeight"`
	ItemWeightUnit              string `json:"ItemWeightUnit"`
	ItemVolume                  string `json:"ItemVolume"`
	ItemVolumeUnit              string `json:"ItemVolumeUnit"`
	TransactionCurrency         string `json:"TransactionCurrency"`
	NetAmount                   string `json:"NetAmount"`
	MaterialGroup               string `json:"MaterialGroup"`
	MaterialPricingGroup        string `json:"MaterialPricingGroup"`
	BillingDocumentDate         string `json:"BillingDocumentDate"`
	Batch                       string `json:"Batch"`
	ProductionPlant             string `json:"ProductionPlant"`
	StorageLocation             string `json:"StorageLocation"`
	DeliveryGroup               string `json:"DeliveryGroup"`
	ShippingPoint               string `json:"ShippingPoint"`
	ShippingType                string `json:"ShippingType"`
	DeliveryPriority            string `json:"DeliveryPriority"`
	IncotermsClassification     string `json:"IncotermsClassification"`
	TaxAmount                   string `json:"TaxAmount"`
	ProductTaxClassification1   string `json:"ProductTaxClassification1"`
	MatlAccountAssignmentGroup  string `json:"MatlAccountAssignmentGroup"`
	CostAmount                  string `json:"CostAmount"`
	CustomerPaymentTerms        string `json:"CustomerPaymentTerms"`
	CustomerGroup               string `json:"CustomerGroup"`
	SalesDocumentRjcnReason     string `json:"SalesDocumentRjcnReason"`
	ItemBillingBlockReason      string `json:"ItemBillingBlockReason"`
	WBSElement                  string `json:"WBSElement"`
	ProfitCenter                string `json:"ProfitCenter"`
	AccountingExchangeRate      string `json:"AccountingExchangeRate"`
	ReferenceSDDocument         string `json:"ReferenceSDDocument"`
	ReferenceSDDocumentItem     string `json:"ReferenceSDDocumentItem"`
	SDProcessStatus             string `json:"SDProcessStatus"`
	DeliveryStatus              string `json:"DeliveryStatus"`
	OrderRelatedBillingStatus   string `json:"OrderRelatedBillingStatus"`
}
